 ; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
libdeps_dir = /tmp/libdeps
extra_configs = 
	lib/OGM-Common/platformio.base.ini
	lib/OGM-Common/platformio.rp2040.ini
	lib/OGM-Common/platformio.esp32.ini
	lib/OFM-UsbExchange/platformio.exchange.ini
	platformio.custom.ini

[BASE]
build_flags = 
	-D OPENKNX
	-D NCN5120
	-D KNX_FLASH_CALLBACK
	-D SMALL_GROUPOBJECT
	-D USE_BINSEARCH
	-D OVERRUN_COUNT=31
	-D EOPR_TIMEOUT=32
	-Iinclude
	-Wuninitialized
	-Wunused-variable
	-Wno-unknown-pragmas
	-Wno-switch
debug_build_flags = 
	-ggdb3
	-O0

[KNX_TP]
build_flags = 
	-D MASK_VERSION=0x07B0

[KNX_IP]
build_flags = 
	-D MASK_VERSION=0x57B0

[KNX_IPTP]
build_flags = 
	-D MASK_VERSION=0x091A

[env]
framework = arduino
monitor_speed = 115200
monitor_filters = 
	direct
lib_ldf_mode = deep+
debug_tool = jlink
debug_extra_cmds = 
	set output-radix 16
extra_scripts = 
	lib/OGM-Common/scripts/pio/prepare.py
	lib/OGM-Common/scripts/pio/show_flash_partitioning.py

[UPLOAD_JLINK]
upload_protocol = jlink

[RP2040_FLASH]
build_flags = 
	-D KNX_FLASH_SIZE=0x8000
	-D KNX_FLASH_OFFSET=0xF4000
	-D OPENKNX_FLASH_SIZE=0x4000
	-D OPENKNX_FLASH_OFFSET=0xFC000

[RP2040]
extends = BASE, RP2040_2MB
upload_protocol = picotool
platform = https://github.com/maxgerhardt/platform-raspberrypi.git#6af38e2
platform_packages = framework-arduinopico @ https://github.com/earlephilhower/arduino-pico/releases/download/4.6.0/rp2040-4.6.0.zip
board = rpipico
board_build.core = earlephilhower
extra_scripts = 
	${env.extra_scripts}
	lib/OGM-Common/scripts/pio/patch_uf2.py
build_flags = 
	${BASE.build_flags}
	${RP2040_FLASH.build_flags}
	-D PIO_FRAMEWORK_ARDUINO_ENABLE_RTTI

[RP2040_develop]
extends = RP2040
build_type = debug
build_flags = 
	-D OPENKNX_WAIT_FOR_SERIAL=5000
	-D OPENKNX_DEBUG
	${RP2040.build_flags}

[RP2040_releases]
extends = RP2040
build_flags = 
	-D OPENKNX_WATCHDOG
	${RP2040.build_flags}

[RP2040_16MB]
board_upload.maximum_size = 16777216
board_build.filesystem_size = 15724544

[RP2040_8MB]
board_upload.maximum_size = 8388608
board_build.filesystem_size = 7340032

[RP2040_4MB]
board_upload.maximum_size = 4194304
board_build.filesystem_size = 3141632

[RP2040_2MB]
board_upload.maximum_size = 2097152
board_build.filesystem_size = 1044480

[RP2040_UPLOAD_USB]

[ESP32]
extends = BASE, ESP32_4MB
platform = https://github.com/pioarduino/platform-espressif32/releases/download/54.03.20/platform-espressif32.zip
board = esp32dev
board_build.filesystem = littlefs
framework = arduino
lib_ldf_mode = chain
extra_scripts = 
	lib/OGM-Common/scripts/pio/prepare.py
	lib/OGM-Common/scripts/pio/create_esp32_image.py
build_flags = 
	${BASE.build_flags}
monitor_filters = 
	esp32_exception_decoder
	${env.monitor_filters}
debug_build_flags = -O0 -ggdb3 -g3
debug_init_break = tbreak setup
debug_tool = esp-prog
upload_protocol = esptool
upload_speed = 460800

[ESP32_develop]
extends = ESP32
build_type = debug
build_flags = 
	-D OPENKNX_DEBUG
	${ESP32.build_flags}

[ESP32_releases]
extends = ESP32
build_flags = 
	-D OPENKNX_WATCHDOG
	${ESP32.build_flags}

[ESP32_UPLOAD_USB]

[UPLOAD_ESP_PROG]
upload_protocol = esp-prog
upload_speed = 921600

[ESP32_4MB]
board_build.partitions = lib/OGM-Common/data/partitions/esp32_4mb.csv

[ESP32_8MB]
board_build.partitions = lib/OGM-Common/data/partitions/esp32_8mb.csv
board_upload.flash_size = 8MB
board_upload.maximum_size = 8388608

[ESP32_16MB]
board_build.partitions = lib/OGM-Common/data/partitions/esp32_16mb.csv
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216

[RP2040_EXCHANGE]
build_flags = 
	-D USE_BLOCK_DEVICE_INTERFACE
	-D EXCHANGE_FLASH_OFFSET=0x00100000
	-D EXCHANGE_FS_SIZE=0x01000000

[RP2040_EXCHANGE_16MB]
extends = RP2040_EXCHANGE, RP2040_16MB
board_build.filesystem_size = 14675968
build_flags = 
	${RP2040_EXCHANGE.build_flags}
	-D EXCHANGE_FLASH_SIZE=0x100000

[RP2040_EXCHANGE_8MB]
extends = RP2040_EXCHANGE, RP2040_8MB
board_build.filesystem_size = 6532800
build_flags = 
	${RP2040_EXCHANGE.build_flags}
	-D EXCHANGE_FLASH_SIZE=0xC0000

[RP2040_EXCHANGE_4MB]
extends = RP2040_EXCHANGE, RP2040_4MB
board_build.filesystem_size = 2616064
build_flags = 
	${RP2040_EXCHANGE.build_flags}
	-D EXCHANGE_FLASH_SIZE=0x80000

[RP2040_EXCHANGE_2MB]
extends = RP2040_EXCHANGE, RP2040_2MB
board_build.filesystem_size = 782336
build_flags = 
	${RP2040_EXCHANGE.build_flags}
	-D EXCHANGE_FLASH_SIZE=0x40000

[custom]
build_flags = 
	-D OPENKNX_WATCHDOG
	-D KNX_ACTIVITYCALLBACK
	-D OPENKNX_LOOPTIME_WARNING=100
	-I lib/OGM-HardwareConfig/include/
	-D USE_TP_RX_QUEUE
	-D OPENKNX_OVERRIDE_MASK_VERSION=0x07B0

[custom_develop]
extends = custom
build_flags = 
	${custom.build_flags}
	-D OPENKNX_HEARTBEAT
	;"-D OPENKNX_TRACE1=Flash"
	"-D OPENKNX_TRACE5=Watchdog"

[custom_releases]
extends = custom
build_flags = 
	${custom.build_flags}

[RP2040_custom]
extends = RP2040, custom
build_flags = 
	-D DUMMY_FLASH_OFFSET=0xF2000
	-D DUMMY_FLASH_SIZE=0x1000
	-D SERIAL_DEBUG=Serial
	-D USE_KNX_DMA_UART=0
	-D USE_KNX_DMA_IRQ=0

[develop_RP2040_BASE]
extends = RP2040_develop, RP2040_custom, custom_develop, RP2040_UPLOAD_USB
build_flags = 
	${RP2040_develop.build_flags}
	${RP2040_custom.build_flags}
	${custom_develop.build_flags}

[env:develop_RP2040_TP]
extends = develop_RP2040_BASE, RP2040_EXCHANGE_2MB
build_flags = 
	${develop_RP2040_BASE.build_flags}
	${RP2040_EXCHANGE_2MB.build_flags}
	${KNX_TP.build_flags}
	-D DEVICE_REG1_BASE

[env:develop_OpenKNXiaoMiniRP2040_TP]
extends = develop_RP2040_BASE, RP2040_EXCHANGE_8MB
build_flags =
  ${develop_RP2040_BASE.build_flags}
  ${RP2040_EXCHANGE_8MB.build_flags}
  ${KNX_TP.build_flags}
  -D OKNXHW_OPENKNXIAO_RP2040_MINI_V1
	-D NEOPIXEL_MODULE
	-D NEOPIXEL_MAX_PHYSICAL_STRIPS=6
	-D NEOPIXEL_MAX_VIRTUAL_STRIPS=1
	-D NEOPIXEL_MAX_SEGMENTS=16


[env:develop_RP2040_IP]
extends = develop_RP2040_BASE, RP2040_EXCHANGE_16MB
build_flags = 
	${develop_RP2040_BASE.build_flags}
	${RP2040_EXCHANGE_16MB.build_flags}
	${KNX_IP.build_flags}
	-D DEVICE_REG1_BASE_IP
	-D KNX_IP_LAN

[env:develop_RP2040_PICOW]
extends = develop_RP2040_BASE
board = rpipicow
build_flags = 
	${develop_RP2040_BASE.build_flags}
	${KNX_IP.build_flags}
	-D KNX_IP_WIFI
	-D BOARD_PIPICOW
	-D OPENKNX_USB_EXCHANGE_IGNORE
	-Os

[env:develop_RP2040_TP_DUALCORE]
extends = env:develop_RP2040_TP
build_flags = 
	${env:develop_RP2040_TP.build_flags}
	-D OPENKNX_DUALCORE

[env:develop_RP2040_TP_JLINK]
extends = env:develop_RP2040_TP, UPLOAD_JLINK

[env:develop_RP2040_TP_DUALCORE_JLINK]
extends = env:develop_RP2040_TP_DUALCORE, UPLOAD_JLINK

[env:develop_RP2040_IP_JLINK]
extends = env:develop_RP2040_IP, UPLOAD_JLINK

[ESP32_custom]
extends = ESP32, custom
build_flags = 
	-D SERIAL_DEBUG=Serial
	-D KNX_SERIAL=Serial2
	-D OPENKNX_USB_EXCHANGE_IGNORE

[env:develop_ESP32_IP]
extends = ESP32_develop, ESP32_custom, custom_develop, ESP32_8MB, ESP32_UPLOAD_USB
lib_deps = https://github.com/mlesniew/PicoMQTT
build_flags = 
	${KNX_IP.build_flags}
	${ESP32_develop.build_flags}
	${ESP32_custom.build_flags}
	${custom_develop.build_flags}
	-D DEVICE_DEV_REG1_LAN_TP_Base_V00_11
	-D KNX_IP_LAN
	-D CONFIG_ETH_ENABLED
	-D OPENKNX_DUALCORE
	-D OPENKNX_MQTT
	-D OPENKNX_USB_EXCHANGE_IGNORE

[env:develop_OpenKNXiaoMiniESP32S3_IP]
extends = ESP32_develop, ESP32_custom, custom_develop, ESP32_8MB, ESP32_UPLOAD_USB
build_flags =
  ${KNX_IP.build_flags}
  ${ESP32_develop.build_flags}
  ${ESP32_custom.build_flags}
  ${custom_develop.build_flags}
  -D OKNXHW_OPENKNXIAO_ESP32S3_MINI_V1
	-D KNX_IP_LAN
  ;-D OPENKNX_DUALCORE
  -D CONFIG_ETH_ENABLED
	-D OPENKNX_USB_EXCHANGE_IGNORE
  ; -D OPENKNX_WATCHDOG_MAX_PERIOD=3
	-D NEOPIXEL_MAX_PHYSICAL_STRIPS=6
	-D NEOPIXEL_MAX_VIRTUAL_STRIPS=1
	-D NEOPIXEL_MAX_SEGMENTS=16

[env:develop_ESP32_WIP]
extends = ESP32_develop, ESP32_custom, custom_develop, ESP32_8MB, ESP32_UPLOAD_USB
build_flags = 
	${KNX_IP.build_flags}
	${ESP32_develop.build_flags}
	${ESP32_custom.build_flags}
	${custom_develop.build_flags}
	-D DEVICE_DEV_REG1_LAN_TP_Base_V00_11
	-D KNX_IP_WIFI
	-D OPENKNX_DUALCORE
lib_deps = makuna/NeoPixelBus@^2.7.5

[env:develop_ESP32_TP]
extends = ESP32_develop, ESP32_custom, custom_develop, ESP32_8MB, ESP32_UPLOAD_USB
lib_deps = makuna/NeoPixelBus@^2.7.5
build_flags = 
	${KNX_TP.build_flags}
	${ESP32_develop.build_flags}
	${ESP32_custom.build_flags}
	${custom_develop.build_flags}
	-D DEVICE_DEV_REG1_LAN_TP_Base_V00_11
	-D CONFIG_ETH_ENABLED

[env:develop_WT32_ETH01]
extends = ESP32_develop, ESP32_custom, custom_develop, ESP32_UPLOAD_USB
build_flags = 
	${KNX_IP.build_flags}
	${ESP32_develop.build_flags}
	${ESP32_custom.build_flags}
	${custom_develop.build_flags}
	-D BOARD_ESP32_WT32_ETH01
	-D CONFIG_ETH_ENABLED
	-D KNX_IP_LAN
board = wt32-eth01

[env:develop_REG1_ESP_DEV_IP]
lib_deps = https://github.com/mlesniew/PicoMQTT
extends = ESP32_develop, ESP32_custom, custom_develop, ESP32_8MB, ESP32_UPLOAD_JTAG
build_flags = 
	${KNX_IP.build_flags}
	${ESP32_develop.build_flags}
	${ESP32_custom.build_flags}
	${custom_develop.build_flags}
	-D DEVICE_DEV_REG1_LAN_TP_Base_V00_11
	-D CONFIG_ETH_ENABLED
	-D KNX_IP_LAN
board = esp32dev

[env:develop_REG1_ESP_DEV_TP]
extends = ESP32_develop, ESP32_custom, custom_develop, ESP32_8MB, ESP32_UPLOAD_USB
build_flags = 
	${KNX_TP.build_flags}
	${ESP32_develop.build_flags}
	${ESP32_custom.build_flags}
	${custom_develop.build_flags}
	-D DEVICE_DEV_REG1_LAN_TP_Base_V00_11
board = esp32dev

[env:develop_REG1_ESP_DEV_TPIP]
lib_deps = https://github.com/mlesniew/PicoMQTT
extends = ESP32_develop, ESP32_custom, custom_develop, ESP32_8MB, ESP32_UPLOAD_USB
build_flags = 
	${KNX_TP.build_flags}
	${ESP32_develop.build_flags}
	${ESP32_custom.build_flags}
	${custom_develop.build_flags}
	-D DEVICE_DEV_REG1_LAN_TP_Base_V00_11
	-D CONFIG_ETH_ENABLED
	-D KNX_IP_LAN
	-D OPENKNX_MQTT
board = esp32dev

[env:release_RP2040_TP]
extends = RP2040_releases, RP2040_custom, RP2040_EXCHANGE_16MB, UPLOAD_JLINK
build_flags = 
	${RP2040_releases.build_flags}
	${RP2040_custom.build_flags}
	${custom_releases.build_flags}
	${RP2040_EXCHANGE_16MB.build_flags}
	${KNX_TP.build_flags}
	-D OKNXHW_REG1_CONTROLLER2040_V1

[env:release_PiPico_BCU_Connector]
extends = RP2040_releases, RP2040_custom, RP2040_EXCHANGE_2MB, RP2040_UPLOAD_USB
build_flags = 
	${RP2040_releases.build_flags}
	${RP2040_custom.build_flags}
	${custom_releases.build_flags}
	${RP2040_EXCHANGE_2MB.build_flags}
	${KNX_TP.build_flags}
	-D OKNXHW_PIPICO_BCU_CONNECTOR

[env:release_ESP32]
extends = ESP32_releases, ESP32_custom
build_flags = 
	${ESP32_releases.build_flags}
	${ESP32_custom.build_flags}
	${custom_releases.build_flags}
	-D BOARD_ESP32_DEV
