// Simple preprocessor-only GPIO extractor
// Usage: g++ -E -P -I<paths> -D<defines> extract_gpio_config_simple.cpp
//
// This file uses preprocessor to expand macros and output KEY=VALUE pairs

// Set default DEVICE_HW_ID if not defined by hardware config
#ifndef DEVICE_HW_ID
#define DEVICE_HW_ID 0x0000
#endif

#include "HardwareConfig.h"

// Macro stringification
#define STRINGIFY(x) #x
#define TO_STRING(x) STRINGIFY(x)

// Expand macro value (extra layer for full expansion)
#define EXPAND(x) x

// Extract Device Info (DEVICE_ID and DEVICE_NAME are already strings)
#ifdef DEVICE_ID
HW_DEVICE_ID=DEVICE_ID
#else
HW_DEVICE_ID="Unknown"
#endif

#ifdef DEVICE_NAME
HW_DEVICE_NAME=DEVICE_NAME
#else
HW_DEVICE_NAME="Unknown Device"
#endif

HW_DEVICE_ID_BIT=EXPAND(DEVICE_HW_ID)

// Build macro names dynamically
#define CONCAT_IMPL(a, b) a##_##b
#define CONCAT(a, b) CONCAT_IMPL(a, b)
#define FEATURE_DEFINE(suffix) CONCAT(FEATURE_PREFIX, suffix)

// Check if GPIO ports are defined
#if defined(NEOPIXEL_HW_GPIO_PORTS) || defined(I2C_HW_GPIO_PORTS) || defined(UART_HW_GPIO_PORTS)
HW_GPIO_PORTS_DEFINED=1

// Output port count
#if defined(NEOPIXEL_HW_PORT_COUNT) || defined(I2C_HW_PORT_COUNT) || defined(UART_HW_PORT_COUNT)
HW_GPIO_PORT_COUNT=EXPAND(FEATURE_DEFINE(PORT_COUNT))
#else
HW_GPIO_PORT_COUNT=0
#endif

// Port 1
#if defined(NEOPIXEL_HW_PORT_1_GPIO) || defined(I2C_HW_PORT_1_GPIO) || defined(UART_HW_PORT_1_GPIO)
HW_GPIO_PORT_1_GPIO_DATA=EXPAND(FEATURE_DEFINE(PORT_1_GPIO))
#if defined(NEOPIXEL_HW_PORT_1_LABEL) || defined(I2C_HW_PORT_1_LABEL) || defined(UART_HW_PORT_1_LABEL)
HW_GPIO_PORT_1_LABEL=TO_STRING(FEATURE_DEFINE(PORT_1_LABEL))
#else
HW_GPIO_PORT_1_LABEL="Port 1"
#endif
#endif

// Port 2
#if defined(NEOPIXEL_HW_PORT_2_GPIO) || defined(I2C_HW_PORT_2_GPIO) || defined(UART_HW_PORT_2_GPIO)
HW_GPIO_PORT_2_GPIO_DATA=EXPAND(FEATURE_DEFINE(PORT_2_GPIO))
#if defined(NEOPIXEL_HW_PORT_2_LABEL) || defined(I2C_HW_PORT_2_LABEL) || defined(UART_HW_PORT_2_LABEL)
HW_GPIO_PORT_2_LABEL=TO_STRING(FEATURE_DEFINE(PORT_2_LABEL))
#else
HW_GPIO_PORT_2_LABEL="Port 2"
#endif
#endif

// Port 3
#if defined(NEOPIXEL_HW_PORT_3_GPIO) || defined(I2C_HW_PORT_3_GPIO) || defined(UART_HW_PORT_3_GPIO)
HW_GPIO_PORT_3_GPIO_DATA=EXPAND(FEATURE_DEFINE(PORT_3_GPIO))
#if defined(NEOPIXEL_HW_PORT_3_LABEL) || defined(I2C_HW_PORT_3_LABEL) || defined(UART_HW_PORT_3_LABEL)
HW_GPIO_PORT_3_LABEL=TO_STRING(FEATURE_DEFINE(PORT_3_LABEL))
#else
HW_GPIO_PORT_3_LABEL="Port 3"
#endif
#endif

// Port 4
#if defined(NEOPIXEL_HW_PORT_4_GPIO) || defined(I2C_HW_PORT_4_GPIO) || defined(UART_HW_PORT_4_GPIO)
HW_GPIO_PORT_4_GPIO_DATA=EXPAND(FEATURE_DEFINE(PORT_4_GPIO))
#if defined(NEOPIXEL_HW_PORT_4_LABEL) || defined(I2C_HW_PORT_4_LABEL) || defined(UART_HW_PORT_4_LABEL)
HW_GPIO_PORT_4_LABEL=TO_STRING(FEATURE_DEFINE(PORT_4_LABEL))
#else
HW_GPIO_PORT_4_LABEL="Port 4"
#endif
#endif

// Port 5
#if defined(NEOPIXEL_HW_PORT_5_GPIO) || defined(I2C_HW_PORT_5_GPIO) || defined(UART_HW_PORT_5_GPIO)
HW_GPIO_PORT_5_GPIO_DATA=EXPAND(FEATURE_DEFINE(PORT_5_GPIO))
#if defined(NEOPIXEL_HW_PORT_5_LABEL) || defined(I2C_HW_PORT_5_LABEL) || defined(UART_HW_PORT_5_LABEL)
HW_GPIO_PORT_5_LABEL=TO_STRING(FEATURE_DEFINE(PORT_5_LABEL))
#else
HW_GPIO_PORT_5_LABEL="Port 5"
#endif
#endif

// Port 6
#if defined(NEOPIXEL_HW_PORT_6_GPIO) || defined(I2C_HW_PORT_6_GPIO) || defined(UART_HW_PORT_6_GPIO)
HW_GPIO_PORT_6_GPIO_DATA=EXPAND(FEATURE_DEFINE(PORT_6_GPIO))
#if defined(NEOPIXEL_HW_PORT_6_LABEL) || defined(I2C_HW_PORT_6_LABEL) || defined(UART_HW_PORT_6_LABEL)
HW_GPIO_PORT_6_LABEL=TO_STRING(FEATURE_DEFINE(PORT_6_LABEL))
#else
HW_GPIO_PORT_6_LABEL="Port 6"
#endif
#endif

// Port 7
#if defined(NEOPIXEL_HW_PORT_7_GPIO) || defined(I2C_HW_PORT_7_GPIO) || defined(UART_HW_PORT_7_GPIO)
HW_GPIO_PORT_7_GPIO_DATA=EXPAND(FEATURE_DEFINE(PORT_7_GPIO))
#if defined(NEOPIXEL_HW_PORT_7_LABEL) || defined(I2C_HW_PORT_7_LABEL) || defined(UART_HW_PORT_7_LABEL)
HW_GPIO_PORT_7_LABEL=TO_STRING(FEATURE_DEFINE(PORT_7_LABEL))
#else
HW_GPIO_PORT_7_LABEL="Port 7"
#endif
#endif

// Port 8
#if defined(NEOPIXEL_HW_PORT_8_GPIO) || defined(I2C_HW_PORT_8_GPIO) || defined(UART_HW_PORT_8_GPIO)
HW_GPIO_PORT_8_GPIO_DATA=EXPAND(FEATURE_DEFINE(PORT_8_GPIO))
#if defined(NEOPIXEL_HW_PORT_8_LABEL) || defined(I2C_HW_PORT_8_LABEL) || defined(UART_HW_PORT_8_LABEL)
HW_GPIO_PORT_8_LABEL=TO_STRING(FEATURE_DEFINE(PORT_8_LABEL))
#else
HW_GPIO_PORT_8_LABEL="Port 8"
#endif
#endif

// Port 9
#if defined(NEOPIXEL_HW_PORT_9_GPIO) || defined(I2C_HW_PORT_9_GPIO) || defined(UART_HW_PORT_9_GPIO)
HW_GPIO_PORT_9_GPIO_DATA=EXPAND(FEATURE_DEFINE(PORT_9_GPIO))
#if defined(NEOPIXEL_HW_PORT_9_LABEL) || defined(I2C_HW_PORT_9_LABEL) || defined(UART_HW_PORT_9_LABEL)
HW_GPIO_PORT_9_LABEL=TO_STRING(FEATURE_DEFINE(PORT_9_LABEL))
#else
HW_GPIO_PORT_9_LABEL="Port 9"
#endif
#endif

// Port 10
#if defined(NEOPIXEL_HW_PORT_10_GPIO) || defined(I2C_HW_PORT_10_GPIO) || defined(UART_HW_PORT_10_GPIO)
HW_GPIO_PORT_10_GPIO_DATA=EXPAND(FEATURE_DEFINE(PORT_10_GPIO))
#if defined(NEOPIXEL_HW_PORT_10_LABEL) || defined(I2C_HW_PORT_10_LABEL) || defined(UART_HW_PORT_10_LABEL)
HW_GPIO_PORT_10_LABEL=TO_STRING(FEATURE_DEFINE(PORT_10_LABEL))
#else
HW_GPIO_PORT_10_LABEL="Port 10"
#endif
#endif

// Port 11
#if defined(NEOPIXEL_HW_PORT_11_GPIO) || defined(I2C_HW_PORT_11_GPIO) || defined(UART_HW_PORT_11_GPIO)
HW_GPIO_PORT_11_GPIO_DATA=EXPAND(FEATURE_DEFINE(PORT_11_GPIO))
#if defined(NEOPIXEL_HW_PORT_11_LABEL) || defined(I2C_HW_PORT_11_LABEL) || defined(UART_HW_PORT_11_LABEL)
HW_GPIO_PORT_11_LABEL=TO_STRING(FEATURE_DEFINE(PORT_11_LABEL))
#else
HW_GPIO_PORT_11_LABEL="Port 11"
#endif
#endif

// Port 12
#if defined(NEOPIXEL_HW_PORT_12_GPIO) || defined(I2C_HW_PORT_12_GPIO) || defined(UART_HW_PORT_12_GPIO)
HW_GPIO_PORT_12_GPIO_DATA=EXPAND(FEATURE_DEFINE(PORT_12_GPIO))
#if defined(NEOPIXEL_HW_PORT_12_LABEL) || defined(I2C_HW_PORT_12_LABEL) || defined(UART_HW_PORT_12_LABEL)
HW_GPIO_PORT_12_LABEL=TO_STRING(FEATURE_DEFINE(PORT_12_LABEL))
#else
HW_GPIO_PORT_12_LABEL="Port 12"
#endif
#endif

// Port 13
#if defined(NEOPIXEL_HW_PORT_13_GPIO) || defined(I2C_HW_PORT_13_GPIO) || defined(UART_HW_PORT_13_GPIO)
HW_GPIO_PORT_13_GPIO_DATA=EXPAND(FEATURE_DEFINE(PORT_13_GPIO))
#if defined(NEOPIXEL_HW_PORT_13_LABEL) || defined(I2C_HW_PORT_13_LABEL) || defined(UART_HW_PORT_13_LABEL)
HW_GPIO_PORT_13_LABEL=TO_STRING(FEATURE_DEFINE(PORT_13_LABEL))
#else
HW_GPIO_PORT_13_LABEL="Port 13"
#endif
#endif

// Port 14
#if defined(NEOPIXEL_HW_PORT_14_GPIO) || defined(I2C_HW_PORT_14_GPIO) || defined(UART_HW_PORT_14_GPIO)
HW_GPIO_PORT_14_GPIO_DATA=EXPAND(FEATURE_DEFINE(PORT_14_GPIO))
#if defined(NEOPIXEL_HW_PORT_14_LABEL) || defined(I2C_HW_PORT_14_LABEL) || defined(UART_HW_PORT_14_LABEL)
HW_GPIO_PORT_14_LABEL=TO_STRING(FEATURE_DEFINE(PORT_14_LABEL))
#else
HW_GPIO_PORT_14_LABEL="Port 14"
#endif
#endif

// Port 15
#if defined(NEOPIXEL_HW_PORT_15_GPIO) || defined(I2C_HW_PORT_15_GPIO) || defined(UART_HW_PORT_15_GPIO)
HW_GPIO_PORT_15_GPIO_DATA=EXPAND(FEATURE_DEFINE(PORT_15_GPIO))
#if defined(NEOPIXEL_HW_PORT_15_LABEL) || defined(I2C_HW_PORT_15_LABEL) || defined(UART_HW_PORT_15_LABEL)
HW_GPIO_PORT_15_LABEL=TO_STRING(FEATURE_DEFINE(PORT_15_LABEL))
#else
HW_GPIO_PORT_15_LABEL="Port 15"
#endif
#endif

// Port 16
#if defined(NEOPIXEL_HW_PORT_16_GPIO) || defined(I2C_HW_PORT_16_GPIO) || defined(UART_HW_PORT_16_GPIO)
HW_GPIO_PORT_16_GPIO_DATA=EXPAND(FEATURE_DEFINE(PORT_16_GPIO))
#if defined(NEOPIXEL_HW_PORT_16_LABEL) || defined(I2C_HW_PORT_16_LABEL) || defined(UART_HW_PORT_16_LABEL)
HW_GPIO_PORT_16_LABEL=TO_STRING(FEATURE_DEFINE(PORT_16_LABEL))
#else
HW_GPIO_PORT_16_LABEL="Port 16"
#endif
#endif

#else
HW_GPIO_PORTS_DEFINED=0
HW_GPIO_PORT_COUNT=0
#endif
