/**
 * @file EffectTypeMapping.h
 * @brief Effect Type ID to EffectPool mapping (auto-generated)
 * 
 * This file is AUTO-GENERATED by scripts/Build-EffectParameters.ps1
 * DO NOT EDIT MANUALLY!
 * 
 * Run the following command to regenerate:
 *   pwsh scripts/Build-EffectParameters.ps1
 */

#pragma once

#error "EffectTypeMapping.h is empty! Run 'pwsh scripts/Build-EffectParameters.ps1' to regenerate."

// This file will be generated by Build-EffectParameters.ps1
// Run the script to generate effect type mapping from EffectPool.cpp