#pragma once

#include "NeoPixel.h"
#include "Segment.h"
#include "effects/Effect.h"
#include "effects/EffectPool.h"
#include <vector>

// Forward declaration
class NeoPixelBusModule;
struct SegmentConfig;

/**
 * @brief Effect Configuration Manager
 *
 * Handles all effect-related configuration and management:
 * - Reading effect types from ETS parameters
 * - Mapping effect types to EffectPool instances
 * - Loading effect-specific parameters (auto-generated by Build-EffectParameters.ps1)
 * - Configuring update speed and auto-update behavior
 *
 * This class is part of the NeoPixelModule refactoring to separate concerns:
 * - EffectConfiguration: Effect setup and parameter loading
 * - ColorManagement: Color correction, brightness, temperature
 * - NeoPixelModule: Main orchestration and KNX handling
 */
class EffectConfiguration
{
  public:
    inline const std::string logPrefix() { return "EffectCfg"; }

    EffectConfiguration(NeoPixelBusModule* module);
    ~EffectConfiguration() = default;

    /**
     * @brief Configure all effects from ETS parameters
     *
     * Reads effect types for each segment, applies effects, loads parameters,
     * and configures global update speed (FPS).
     */
    void configureEffects();

    /**
     * @brief Apply an effect to a segment
     *
     * @param segment Target segment
     * @param effectType Effect type ID (0-20+)
     */
    void applyEffectToSegment(Segment* segment, uint8_t effectType);

    /**
     * @brief Setup effect configuration (load parameters)
     *
     * Loads effect-specific parameters from ETS (auto-generated mappings).
     * Also handles mirror effect configuration.
     *
     * @param segment Segment with effect to configure
     * @param loadDefaultColor If true, loads default color from ETS (for startup). If false, keeps current color (for effect changes)
     */
    void setupEffectConfiguration(Segment* segment, bool loadDefaultColor = false);

    // Note: getEffectFromType() is now a global function in EffectTypeMapping.h (auto-generated)

  private:
    NeoPixelBusModule* _module; // Parent module for parameter access
};
