// AUTO-GENERATED by scripts/Build-EffectParameters.ps1
// DO NOT EDIT MANUALLY - Changes will be overwritten!

#ifndef EFFECT_PARAMETER_MAPPING_H
#define EFFECT_PARAMETER_MAPPING_H

#pragma once

#include "knxprod.h"
#include "../lib/OFM-NeoPixel/src/effects/Effect.h"
#include "../lib/OFM-NeoPixel/src/Segment.h"

/**
 * @brief Load effect-specific parameters from EEPROM and apply to effect instance
 * 
 * This function reads effect-specific parameters that were automatically generated
 * from Effect*.h headers via Build-EffectParameters.ps1. Parameters are stored in
 * EEPROM at offset 14+ within each segment memory block.
 * 
 * @param effect Effect instance to configure
 * @param segment Segment instance (for setParameter context)
 * @param effectID Effect type ID (0-21)
 * @param channelIndex Channel/Segment index (0-15) for parameter access
 */
inline void loadEffectParameters(Effect* effect, Segment* segment, uint8_t effectID, uint8_t channelIndex)
{
    if (!effect || !segment) return;
    
    uint8_t paramCount = effect->getParameterCount();
    if (paramCount == 0) return;  // No parameters to load
    
    // Set channel index for ParamNEO_* macro expansion
    uint8_t _channelIndex = channelIndex;
    
    // Map effectID to parameter loading code
    // Macro names match OpenKNXproducer format: ParamNEO_NEO{EffectName}{ParamName}
    // (automatically derived from Parameter Name attribute in XML)
    
    switch (effectID)
    {
        case 1:  // Wipe Effect
            if (paramCount >= 1) effect->setParameter(segment, 0, ParamNEO_NEOWipeSpeed);
            if (paramCount >= 2) effect->setParameter(segment, 1, ParamNEO_NEOWipeDirection);
            break;
            
        case 2:  // Rainbow Effect
            if (paramCount >= 1) effect->setParameter(segment, 0, ParamNEO_NEORainbowSpeed);
            if (paramCount >= 2) effect->setParameter(segment, 1, ParamNEO_NEORainbowDelta);
            break;
            
        case 3:  // Rainbow Cycle Effect
            if (paramCount >= 1) effect->setParameter(segment, 0, ParamNEO_NEORainbowCycleSpeed);
            if (paramCount >= 2) effect->setParameter(segment, 1, ParamNEO_NEORainbowCycleSaturation);
            if (paramCount >= 3) effect->setParameter(segment, 2, ParamNEO_NEORainbowCycleDensity);
            if (paramCount >= 4) effect->setParameter(segment, 3, ParamNEO_NEORainbowCycleReverse);
            break;
            
        case 4:  // Pride2015 Effect
            if (paramCount >= 1) effect->setParameter(segment, 0, ParamNEO_NEOPride2015Speed);
            break;
            
        case 5:  // Confetti Effect
            if (paramCount >= 1) effect->setParameter(segment, 0, ParamNEO_NEOConfettiFadeSpeed);
            if (paramCount >= 2) effect->setParameter(segment, 1, ParamNEO_NEOConfettiSaturation);
            break;
            
        case 6:  // Juggle Effect
            if (paramCount >= 1) effect->setParameter(segment, 0, ParamNEO_NEOJuggleSpeed);
            if (paramCount >= 2) effect->setParameter(segment, 1, ParamNEO_NEOJuggleNumDots);
            if (paramCount >= 3) effect->setParameter(segment, 2, ParamNEO_NEOJuggleFadeSpeed);
            if (paramCount >= 4) effect->setParameter(segment, 3, ParamNEO_NEOJuggleHueOffset);
            break;
            
        case 7:  // BPM Effect
            if (paramCount >= 1) effect->setParameter(segment, 0, ParamNEO_NEOBPMBPM);
            if (paramCount >= 2) effect->setParameter(segment, 1, ParamNEO_NEOBPMHue);
            break;
            
        case 8:  // Cylon Effect
            if (paramCount >= 1) effect->setParameter(segment, 0, ParamNEO_NEOCylonSpeed);
            if (paramCount >= 2) effect->setParameter(segment, 1, ParamNEO_NEOCylonHue);
            if (paramCount >= 3) effect->setParameter(segment, 2, ParamNEO_NEOCylonEyeSize);
            if (paramCount >= 4) effect->setParameter(segment, 3, ParamNEO_NEOCylonFadeAmount);
            break;
            
        case 9:  // RGBWTest Effect
            if (paramCount >= 1) effect->setParameter(segment, 0, ParamNEO_NEORGBWTestPhaseDuration);
            break;
            
        case 10:  // GarageDoor Effect
            if (paramCount >= 1) effect->setParameter(segment, 0, ParamNEO_NEOGarageDoorPhase);
            if (paramCount >= 2) effect->setParameter(segment, 1, ParamNEO_NEOGarageDoorArrowSize);
            if (paramCount >= 3) effect->setParameter(segment, 2, ParamNEO_NEOGarageDoorArrowSpeed);
            if (paramCount >= 4) effect->setParameter(segment, 3, ParamNEO_NEOGarageDoorRunwayGroupSize);
            if (paramCount >= 5) effect->setParameter(segment, 4, ParamNEO_NEOGarageDoorRunwaySpeed);
            if (paramCount >= 6) effect->setParameter(segment, 5, ParamNEO_NEOGarageDoorBreathingSpeed);
            if (paramCount >= 7) effect->setParameter(segment, 6, ParamNEO_NEOGarageDoorOpeningDuration);
            if (paramCount >= 8) effect->setParameter(segment, 7, ParamNEO_NEOGarageDoorRunwayDuration);
            break;
            
        case 11:  // Fire Effect
            if (paramCount >= 1) effect->setParameter(segment, 0, ParamNEO_NEOFireSpeed);
            if (paramCount >= 2) effect->setParameter(segment, 1, ParamNEO_NEOFireCooling);
            if (paramCount >= 3) effect->setParameter(segment, 2, ParamNEO_NEOFireSparking);
            if (paramCount >= 4) effect->setParameter(segment, 3, ParamNEO_NEOFireReverseDirection);
            if (paramCount >= 5) effect->setParameter(segment, 4, ParamNEO_NEOFireBlueFireMode);
            break;
            
        case 12:  // Theater Chase Effect
            if (paramCount >= 1) effect->setParameter(segment, 0, ParamNEO_NEOTheaterChaseSpeed);
            if (paramCount >= 2) effect->setParameter(segment, 1, ParamNEO_NEOTheaterChaseSpacing);
            if (paramCount >= 3) effect->setParameter(segment, 2, ParamNEO_NEOTheaterChaseDotSize);
            if (paramCount >= 4) effect->setParameter(segment, 3, ParamNEO_NEOTheaterChaseTrailMode);
            break;
            
        case 13:  // Theater Chase Rainbow Effect
            if (paramCount >= 1) effect->setParameter(segment, 0, ParamNEO_NEOTheaterChaseRainbowSpeed);
            if (paramCount >= 2) effect->setParameter(segment, 1, ParamNEO_NEOTheaterChaseRainbowSpacing);
            if (paramCount >= 3) effect->setParameter(segment, 2, ParamNEO_NEOTheaterChaseRainbowDotSize);
            if (paramCount >= 4) effect->setParameter(segment, 3, ParamNEO_NEOTheaterChaseRainbowColorSpeed);
            if (paramCount >= 5) effect->setParameter(segment, 4, ParamNEO_NEOTheaterChaseRainbowTrailMode);
            break;
            
        case 14:  // Sinelon Effect
            if (paramCount >= 1) effect->setParameter(segment, 0, ParamNEO_NEOSinelonSpeed);
            if (paramCount >= 2) effect->setParameter(segment, 1, ParamNEO_NEOSinelonFadeRate);
            if (paramCount >= 3) effect->setParameter(segment, 2, ParamNEO_NEOSinelonDotSize);
            if (paramCount >= 4) effect->setParameter(segment, 3, ParamNEO_NEOSinelonRainbowMode);
            if (paramCount >= 5) effect->setParameter(segment, 4, ParamNEO_NEOSinelonBounceMode);
            break;
            
        case 15:  // Twinkle Effect
            if (paramCount >= 1) effect->setParameter(segment, 0, ParamNEO_NEOTwinkleSpeed);
            if (paramCount >= 2) effect->setParameter(segment, 1, ParamNEO_NEOTwinkleFadeRate);
            if (paramCount >= 3) effect->setParameter(segment, 2, ParamNEO_NEOTwinkleDensity);
            if (paramCount >= 4) effect->setParameter(segment, 3, ParamNEO_NEOTwinkleRainbowMode);
            if (paramCount >= 5) effect->setParameter(segment, 4, ParamNEO_NEOTwinkleVariableBrightness);
            break;
            
        case 16:  // Sparkle Effect
            if (paramCount >= 1) effect->setParameter(segment, 0, ParamNEO_NEOSparkleSpeed);
            if (paramCount >= 2) effect->setParameter(segment, 1, ParamNEO_NEOSparkleFadeRate);
            if (paramCount >= 3) effect->setParameter(segment, 2, ParamNEO_NEOSparkleSparkleCount);
            if (paramCount >= 4) effect->setParameter(segment, 3, ParamNEO_NEOSparkleProbability);
            if (paramCount >= 5) effect->setParameter(segment, 4, ParamNEO_NEOSparkleWhiteOnly);
            if (paramCount >= 6) effect->setParameter(segment, 5, ParamNEO_NEOSparkleBurstMode);
            break;
            
        case 17:  // Breathing Effect
            if (paramCount >= 1) effect->setParameter(segment, 0, ParamNEO_NEOBreathingSpeed);
            if (paramCount >= 2) effect->setParameter(segment, 1, ParamNEO_NEOBreathingMinBrightness);
            if (paramCount >= 3) effect->setParameter(segment, 2, ParamNEO_NEOBreathingCurve);
            if (paramCount >= 4) effect->setParameter(segment, 3, ParamNEO_NEOBreathingHoldAtPeak);
            if (paramCount >= 5) effect->setParameter(segment, 4, ParamNEO_NEOBreathingRainbowBreathing);
            break;
            
        case 18:  // Strobe Effect
            if (paramCount >= 1) effect->setParameter(segment, 0, ParamNEO_NEOStrobeSpeed);
            if (paramCount >= 2) effect->setParameter(segment, 1, ParamNEO_NEOStrobeOnRatio);
            if (paramCount >= 3) effect->setParameter(segment, 2, ParamNEO_NEOStrobeMinBrightness);
            if (paramCount >= 4) effect->setParameter(segment, 3, ParamNEO_NEOStrobeRandomTiming);
            if (paramCount >= 5) effect->setParameter(segment, 4, ParamNEO_NEOStrobeRainbowStrobe);
            break;
            
        case 19:  // Pulse Effect
            if (paramCount >= 1) effect->setParameter(segment, 0, ParamNEO_NEOPulseSpeed);
            if (paramCount >= 2) effect->setParameter(segment, 1, ParamNEO_NEOPulsePulseWidth);
            if (paramCount >= 3) effect->setParameter(segment, 2, ParamNEO_NEOPulseGamma);
            if (paramCount >= 4) effect->setParameter(segment, 3, ParamNEO_NEOPulseSharpPulse);
            if (paramCount >= 5) effect->setParameter(segment, 4, ParamNEO_NEOPulseRainbowPulse);
            break;
            
        case 20:  // Comet Effect
            if (paramCount >= 1) effect->setParameter(segment, 0, ParamNEO_NEOCometSpeed);
            if (paramCount >= 2) effect->setParameter(segment, 1, ParamNEO_NEOCometFadeRate);
            if (paramCount >= 3) effect->setParameter(segment, 2, ParamNEO_NEOCometTailLength);
            if (paramCount >= 4) effect->setParameter(segment, 3, ParamNEO_NEOCometBounceMode);
            if (paramCount >= 5) effect->setParameter(segment, 4, ParamNEO_NEOCometRainbowMode);
            break;
            
        case 21:  // Meteor Effect
            if (paramCount >= 1) effect->setParameter(segment, 0, ParamNEO_NEOMeteorSpeed);
            if (paramCount >= 2) effect->setParameter(segment, 1, ParamNEO_NEOMeteorMeteorSize);
            if (paramCount >= 3) effect->setParameter(segment, 2, ParamNEO_NEOMeteorFrequency);
            if (paramCount >= 4) effect->setParameter(segment, 3, ParamNEO_NEOMeteorRandomColors);
            if (paramCount >= 5) effect->setParameter(segment, 4, ParamNEO_NEOMeteorMultiMeteor);
            break;
            
        case 22:  // Noise Effect
            if (paramCount >= 1) effect->setParameter(segment, 0, ParamNEO_NEONoiseSpeed);
            if (paramCount >= 2) effect->setParameter(segment, 1, ParamNEO_NEONoiseScale);
            if (paramCount >= 3) effect->setParameter(segment, 2, ParamNEO_NEONoiseSaturation);
            if (paramCount >= 4) effect->setParameter(segment, 3, ParamNEO_NEONoiseHueOffset);
            break;
            
        case 23:  // Palette Effect
            if (paramCount >= 1) effect->setParameter(segment, 0, ParamNEO_NEOPaletteSpeed);
            if (paramCount >= 2) effect->setParameter(segment, 1, ParamNEO_NEOPalettePalette);
            if (paramCount >= 3) effect->setParameter(segment, 2, ParamNEO_NEOPaletteBlend);
            if (paramCount >= 4) effect->setParameter(segment, 3, ParamNEO_NEOPaletteSpacing);
            break;
            
        case 24:  // Blitz Effect
            if (paramCount >= 1) effect->setParameter(segment, 0, ParamNEO_NEOBlitzSpeed);
            if (paramCount >= 2) effect->setParameter(segment, 1, ParamNEO_NEOBlitzWidth);
            if (paramCount >= 3) effect->setParameter(segment, 2, ParamNEO_NEOBlitzDecay);
            if (paramCount >= 4) effect->setParameter(segment, 3, ParamNEO_NEOBlitzHue);
            break;
            
        case 25:  // Gradient Effect
            if (paramCount >= 1) effect->setParameter(segment, 0, ParamNEO_NEOGradientSpeed);
            if (paramCount >= 2) effect->setParameter(segment, 1, ParamNEO_NEOGradientStartHue);
            if (paramCount >= 3) effect->setParameter(segment, 2, ParamNEO_NEOGradientEndHue);
            if (paramCount >= 4) effect->setParameter(segment, 3, ParamNEO_NEOGradientSaturation);
            break;
            
        // Effects without parameters: 0,1,3,8,9,10,11,12,13,14,15,16,17,18,19,20,21
        default:
            // No effect-specific parameters to load
            break;
    }
}

#endif // EFFECT_PARAMETER_MAPPING_H

