/**
 * @file HardwareMappingData.h
 * @brief Hardware ID to Index mapping (auto-generated)
 * 
 * This file is AUTO-GENERATED by scripts/Build-HardwareConfig.ps1
 * DO NOT EDIT MANUALLY!
 * 
 * Run the following command to regenerate:
 *   pwsh scripts/Build-HardwareConfig.ps1 -FeatureName "NeoPixel" -DefinesPrefix "NEOPIXEL_HW"
 * Or use the wrapper:
 *   pwsh scripts/Build-HardwareConfigTemplates.ps1
 */

#pragma once

#error "HardwareMappingData.h is empty! Run 'pwsh scripts/Build-HardwareConfigTemplates.ps1' to regenerate."

// This file will be generated by Build-HardwareConfig.ps1
// Run the script to generate hardware ID mapping from platformio.hardware.ini