#pragma once

#include <cstdint>

// Include auto-generated hardware mapping (generated by Build-HardwareConfig.ps1)
#include "HardwareMappingData.h"

/**
 * @brief Get the currently selected hardware index from ETS parameters
 * 
 * Reads the NEO_NeoPixelHardwareSelect parameter and maps it to the hardware index.
 * If in compile-time mode (DEVICE_HW_ID defined), uses that instead.
 * 
 * @return Hardware index (0-7)
 */
inline uint8_t getCurrentHardwareIndex()
{
    #ifdef DEVICE_HW_ID
        // Compile-time mode: Use DEVICE_HW_ID from hardware config
        return HardwareMapping::mapDeviceHwIdToIndex(DEVICE_HW_ID);
    #else
        // Runtime mode: Read from ETS parameter (requires knxprod.h)
        #ifdef ParamNEO_NEO_NeoPixelHardwareSelect
            uint16_t selectedHwId = (uint16_t)ParamNEO_NEO_NeoPixelHardwareSelect;
            return HardwareMapping::mapDeviceHwIdToIndex(selectedHwId);
        #else
            return 0; // Fallback to HW0
        #endif
    #endif
}

/**
 * @brief Get GPIO Data Port parameter value for current hardware
 * 
 * Reads the hardware-specific GPIO data port parameter based on the current hardware index.
 * Returns special values:
 * - 15: Dummy/Not selected
 * - 10: Manual GPIO configuration
 * - 0-9: Hardware-specific port index (maps to actual GPIO via platformio.hardware.ini)
 * 
 * @param stripIndex Strip index (1-based, as used in knxprod.h macros)
 * @param hwIndex Hardware index (0-7), if 255 (default) uses current hardware
 * @return GPIO port selection value
 */
inline uint8_t getGpioDataPortForHw(uint8_t stripIndex, uint8_t hwIndex = 255)
{
    if (hwIndex == 255)
    {
        hwIndex = getCurrentHardwareIndex();
    }
    
    // Use macro concatenation to select the correct parameter
    // ParamNEOSTRIP_NEOGPIODataPortHW0 to HW7
    #ifdef ParamNEOSTRIP_NEOGPIODataPortHW0
        // Set _channelIndex for knxprod.h macros that use NEOSTRIP_ParamCalcIndex
        uint8_t _channelIndex = stripIndex;
        
        switch (hwIndex)
        {
            case 0: return (uint8_t)ParamNEOSTRIP_NEOGPIODataPortHW0;
            case 1: return (uint8_t)ParamNEOSTRIP_NEOGPIODataPortHW1;
            case 2: return (uint8_t)ParamNEOSTRIP_NEOGPIODataPortHW2;
            case 3: return (uint8_t)ParamNEOSTRIP_NEOGPIODataPortHW3;
            case 4: return (uint8_t)ParamNEOSTRIP_NEOGPIODataPortHW4;
            case 5: return (uint8_t)ParamNEOSTRIP_NEOGPIODataPortHW5;
            case 6: return (uint8_t)ParamNEOSTRIP_NEOGPIODataPortHW6;
            case 7: return (uint8_t)ParamNEOSTRIP_NEOGPIODataPortHW7;
            default: return 15; // Dummy value
        }
    #else
        return 15; // Not configured
    #endif
}

/**
 * @brief Get GPIO Clock Port parameter value for current hardware
 * 
 * Similar to getGpioDataPortForHw but for clock pins (SPI protocols only).
 * 
 * @param stripIndex Strip index (1-based, as used in knxprod.h macros)
 * @param hwIndex Hardware index (0-7), if 255 (default) uses current hardware
 * @return GPIO clock port selection value
 */
inline uint8_t getGpioClockPortForHw(uint8_t stripIndex, uint8_t hwIndex = 255)
{
    if (hwIndex == 255)
    {
        hwIndex = getCurrentHardwareIndex();
    }
    
    // Use macro concatenation to select the correct parameter
    // ParamNEOSTRIP_NEOGPIOClockPortHW0 to HW7
    #ifdef ParamNEOSTRIP_NEOGPIOClockPortHW0
        // Set _channelIndex for knxprod.h macros that use NEOSTRIP_ParamCalcIndex
        uint8_t _channelIndex = stripIndex;
        
        switch (hwIndex)
        {
            case 0: return (uint8_t)ParamNEOSTRIP_NEOGPIOClockPortHW0;
            case 1: return (uint8_t)ParamNEOSTRIP_NEOGPIOClockPortHW1;
            case 2: return (uint8_t)ParamNEOSTRIP_NEOGPIOClockPortHW2;
            case 3: return (uint8_t)ParamNEOSTRIP_NEOGPIOClockPortHW3;
            case 4: return (uint8_t)ParamNEOSTRIP_NEOGPIOClockPortHW4;
            case 5: return (uint8_t)ParamNEOSTRIP_NEOGPIOClockPortHW5;
            case 6: return (uint8_t)ParamNEOSTRIP_NEOGPIOClockPortHW6;
            case 7: return (uint8_t)ParamNEOSTRIP_NEOGPIOClockPortHW7;
            default: return 15; // Dummy value
        }
    #else
        return 15; // Not configured
    #endif
}

/**
 * @brief Map hardware port index to actual GPIO number
 * 
 * Converts a port index (0-9) to the actual GPIO pin number using compile-time defines
 * from platformio.hardware.ini (NEOPIXEL_HW_PORT_N_GPIO).
 * 
 * Port indices map to NEOPIXEL_HW_PORT_{index+1}_GPIO defines:
 * - Index 0 → NEOPIXEL_HW_PORT_1_GPIO
 * - Index 1 → NEOPIXEL_HW_PORT_2_GPIO
 * - etc.
 * 
 * @param portIndex Port index (0-9) from ETS parameter
 * @return Actual GPIO pin number, or 255 if invalid/not defined
 */
inline uint8_t mapPortIndexToGpio(uint8_t portIndex)
{
    // Port indices 0-9 map to NEOPIXEL_HW_PORT_1_GPIO through NEOPIXEL_HW_PORT_10_GPIO
    switch (portIndex)
    {
        #ifdef NEOPIXEL_HW_PORT_1_GPIO
        case 0: return NEOPIXEL_HW_PORT_1_GPIO;
        #endif
        #ifdef NEOPIXEL_HW_PORT_2_GPIO
        case 1: return NEOPIXEL_HW_PORT_2_GPIO;
        #endif
        #ifdef NEOPIXEL_HW_PORT_3_GPIO
        case 2: return NEOPIXEL_HW_PORT_3_GPIO;
        #endif
        #ifdef NEOPIXEL_HW_PORT_4_GPIO
        case 3: return NEOPIXEL_HW_PORT_4_GPIO;
        #endif
        #ifdef NEOPIXEL_HW_PORT_5_GPIO
        case 4: return NEOPIXEL_HW_PORT_5_GPIO;
        #endif
        #ifdef NEOPIXEL_HW_PORT_6_GPIO
        case 5: return NEOPIXEL_HW_PORT_6_GPIO;
        #endif
        #ifdef NEOPIXEL_HW_PORT_7_GPIO
        case 6: return NEOPIXEL_HW_PORT_7_GPIO;
        #endif
        #ifdef NEOPIXEL_HW_PORT_8_GPIO
        case 7: return NEOPIXEL_HW_PORT_8_GPIO;
        #endif
        #ifdef NEOPIXEL_HW_PORT_9_GPIO
        case 8: return NEOPIXEL_HW_PORT_9_GPIO;
        #endif
        #ifdef NEOPIXEL_HW_PORT_10_GPIO
        case 9: return NEOPIXEL_HW_PORT_10_GPIO;
        #endif
        default: return 255; // Invalid/not defined
    }
}

/**
 * @brief Check if hardware-assisted GPIO mode is active
 * 
 * Returns true if a valid hardware port is selected (not manual, not dummy).
 * 
 * @param portSelection Port selection value from getGpioDataPortForHw() or getGpioClockPortForHw()
 * @return true if hardware port is selected, false if manual (10) or dummy (15)
 */
inline bool isHardwarePortSelected(uint8_t portSelection)
{
    return portSelection < 10; // 0-9 are valid hardware ports, 10=manual, 15=dummy
}

/**
 * @brief Get actual GPIO number for data port
 * 
 * High-level function that:
 * 1. Checks if manual mode is enabled
 * 2. If not manual, reads hardware-specific port index
 * 3. Maps port index to actual GPIO number
 * 
 * @param stripIndex Strip index (1-based)
 * @param manualGpio Manual GPIO number (from ParamNEOSTRIP_NEODataGPIO)
 * @param isManual Manual mode flag (from ParamNEOSTRIP_NEOGPIOManual)
 * @return Actual GPIO pin number
 */
inline uint8_t getActualDataGpio(uint8_t stripIndex, uint8_t manualGpio, bool isManual)
{
    if (isManual)
    {
        return manualGpio;
    }
    
    uint8_t portIndex = getGpioDataPortForHw(stripIndex);
    if (isHardwarePortSelected(portIndex))
    {
        return mapPortIndexToGpio(portIndex);
    }
    
    // Fallback to manual GPIO if hardware port not properly selected
    return manualGpio;
}

/**
 * @brief Get actual GPIO number for clock port (SPI only)
 * 
 * Similar to getActualDataGpio but for clock pins.
 * 
 * @param stripIndex Strip index (1-based)
 * @param manualGpio Manual GPIO number (from ParamNEOSTRIP_NEOClockGPIO)
 * @param isManual Manual mode flag (from ParamNEOSTRIP_NEOGPIOManual)
 * @return Actual GPIO pin number
 */
inline uint8_t getActualClockGpio(uint8_t stripIndex, uint8_t manualGpio, bool isManual)
{
    if (isManual)
    {
        return manualGpio;
    }
    
    uint8_t portIndex = getGpioClockPortForHw(stripIndex);
    if (isHardwarePortSelected(portIndex))
    {
        return mapPortIndexToGpio(portIndex);
    }
    
    // Fallback to manual GPIO if hardware port not properly selected
    return manualGpio;
}
