#pragma once

#include <cstdint>

// Include auto-generated hardware mapping (generated by Build-HardwareConfig.ps1)
#include "HardwareMappingData.h"

// Hardware index values and GPIO port selection values use different domains.
// Keeping them named avoids confusing a hardware index like 15 with the
// port-selection sentinel value 15 (= dummy / not selected).
constexpr uint8_t CURRENT_HARDWARE_INDEX = 255;
constexpr uint8_t INVALID_GPIO = 255;
constexpr uint8_t MAX_HARDWARE_PORT_INDEX = 9;
constexpr uint8_t MANUAL_GPIO_PORT_SELECTION = 10;
constexpr uint8_t DUMMY_GPIO_PORT_SELECTION = 15;

/**
 * @brief Get the currently selected hardware index from ETS parameters
 *
 * In runtime mode, reads the NEO_NeoPixelHardwareSelect parameter, which already
 * stores the generated hardware index.
 * In compile-time mode (DEVICE_HW_ID defined), converts DEVICE_HW_ID to the
 * generated hardware index.
 *
 * @return Hardware index (0-based)
 */
inline uint8_t getCurrentHardwareIndex()
{
#ifdef DEVICE_HW_ID
    // Compile-time mode: Use DEVICE_HW_ID from hardware config
    return HardwareMapping::mapDeviceHwIdToIndex(DEVICE_HW_ID);
#else
    // Runtime mode: Read hardware index from ETS parameter (requires knxprod.h)
    #ifdef ParamNEO_NeoPixelHardwareSelect
    return (uint8_t)ParamNEO_NeoPixelHardwareSelect;
    #else
    return 0; // Fallback to HW0
    #endif
#endif
}

/**
 * @brief Get the data-port selection code for a hardware index
 *
 * Uses the selected hardware index to read the matching hardware-specific ETS
 * parameter. The returned value is a port-selection code, not a hardware index.
 * Special port-selection values:
 * - 15: Dummy/Not selected
 * - 10: Manual GPIO configuration
 * - 0-9: Hardware-specific port index (maps to actual GPIO via platformio.hardware.ini)
 *
 * @param stripIndex Strip index (1-based, as used in knxprod.h macros)
 * @param hardwareIndex Hardware index (0-based), if 255 (default) uses current hardware
 * @return Port-selection value for the selected hardware
 */
inline uint8_t getDataPortSelectionForHardwareIndex(uint8_t stripIndex, uint8_t hardwareIndex = CURRENT_HARDWARE_INDEX)
{
    if (hardwareIndex == CURRENT_HARDWARE_INDEX)
    {
        hardwareIndex = getCurrentHardwareIndex();
    }

// Select the per-hardware ETS parameter using the hardware index.
#ifdef ParamNEOSTRIP_NEOGPIODataPortHW0
    // Set _channelIndex for knxprod.h macros that use NEOSTRIP_ParamCalcIndex
    uint8_t _channelIndex = stripIndex;

    switch (hardwareIndex)
    {
    #ifdef ParamNEOSTRIP_NEOGPIODataPortHW0
        case 0: return (uint8_t)ParamNEOSTRIP_NEOGPIODataPortHW0;
    #endif
    #ifdef ParamNEOSTRIP_NEOGPIODataPortHW1
        case 1: return (uint8_t)ParamNEOSTRIP_NEOGPIODataPortHW1;
    #endif
    #ifdef ParamNEOSTRIP_NEOGPIODataPortHW2
        case 2: return (uint8_t)ParamNEOSTRIP_NEOGPIODataPortHW2;
    #endif
    #ifdef ParamNEOSTRIP_NEOGPIODataPortHW3
        case 3: return (uint8_t)ParamNEOSTRIP_NEOGPIODataPortHW3;
    #endif
    #ifdef ParamNEOSTRIP_NEOGPIODataPortHW4
        case 4: return (uint8_t)ParamNEOSTRIP_NEOGPIODataPortHW4;
    #endif
    #ifdef ParamNEOSTRIP_NEOGPIODataPortHW5
        case 5: return (uint8_t)ParamNEOSTRIP_NEOGPIODataPortHW5;
    #endif
    #ifdef ParamNEOSTRIP_NEOGPIODataPortHW6
        case 6: return (uint8_t)ParamNEOSTRIP_NEOGPIODataPortHW6;
    #endif
    #ifdef ParamNEOSTRIP_NEOGPIODataPortHW7
        case 7: return (uint8_t)ParamNEOSTRIP_NEOGPIODataPortHW7;
    #endif
    #ifdef ParamNEOSTRIP_NEOGPIODataPortHW8
        case 8: return (uint8_t)ParamNEOSTRIP_NEOGPIODataPortHW8;
    #endif
    #ifdef ParamNEOSTRIP_NEOGPIODataPortHW9
        case 9: return (uint8_t)ParamNEOSTRIP_NEOGPIODataPortHW9;
    #endif
    #ifdef ParamNEOSTRIP_NEOGPIODataPortHW10
        case 10: return (uint8_t)ParamNEOSTRIP_NEOGPIODataPortHW10;
    #endif
    #ifdef ParamNEOSTRIP_NEOGPIODataPortHW11
        case 11: return (uint8_t)ParamNEOSTRIP_NEOGPIODataPortHW11;
    #endif
    #ifdef ParamNEOSTRIP_NEOGPIODataPortHW12
        case 12: return (uint8_t)ParamNEOSTRIP_NEOGPIODataPortHW12;
    #endif
    #ifdef ParamNEOSTRIP_NEOGPIODataPortHW13
        case 13: return (uint8_t)ParamNEOSTRIP_NEOGPIODataPortHW13;
    #endif
    #ifdef ParamNEOSTRIP_NEOGPIODataPortHW14
        case 14: return (uint8_t)ParamNEOSTRIP_NEOGPIODataPortHW14;
    #endif
    #ifdef ParamNEOSTRIP_NEOGPIODataPortHW15
        case 15: return (uint8_t)ParamNEOSTRIP_NEOGPIODataPortHW15;
    #endif
    #ifdef ParamNEOSTRIP_NEOGPIODataPortHW16
        case 16: return (uint8_t)ParamNEOSTRIP_NEOGPIODataPortHW16;
    #endif
    #ifdef ParamNEOSTRIP_NEOGPIODataPortHW17
        case 17: return (uint8_t)ParamNEOSTRIP_NEOGPIODataPortHW17;
    #endif
    #ifdef ParamNEOSTRIP_NEOGPIODataPortHW18
        case 18: return (uint8_t)ParamNEOSTRIP_NEOGPIODataPortHW18;
    #endif
    #ifdef ParamNEOSTRIP_NEOGPIODataPortHW19
        case 19: return (uint8_t)ParamNEOSTRIP_NEOGPIODataPortHW19;
    #endif
    #ifdef ParamNEOSTRIP_NEOGPIODataPortHW20
        case 20: return (uint8_t)ParamNEOSTRIP_NEOGPIODataPortHW20;
    #endif
    #ifdef ParamNEOSTRIP_NEOGPIODataPortHW21
        case 21: return (uint8_t)ParamNEOSTRIP_NEOGPIODataPortHW21;
    #endif
        default: return DUMMY_GPIO_PORT_SELECTION;
    }
#else
    return DUMMY_GPIO_PORT_SELECTION;
#endif
}

/**
 * @brief Get the clock-port selection code for a hardware index
 *
 * Similar to getDataPortSelectionForHardwareIndex but for clock pins used by
 * SPI-style LED protocols. The returned value is a port-selection code, not a
 * hardware index.
 *
 * @param stripIndex Strip index (1-based, as used in knxprod.h macros)
 * @param hardwareIndex Hardware index (0-based), if 255 (default) uses current hardware
 * @return Port-selection value for the selected hardware clock pin
 */
inline uint8_t getClockPortSelectionForHardwareIndex(uint8_t stripIndex, uint8_t hardwareIndex = CURRENT_HARDWARE_INDEX)
{
    if (hardwareIndex == CURRENT_HARDWARE_INDEX)
    {
        hardwareIndex = getCurrentHardwareIndex();
    }

// Select the per-hardware ETS parameter using the hardware index.
#ifdef ParamNEOSTRIP_NEOGPIOClockPortHW0
    // Set _channelIndex for knxprod.h macros that use NEOSTRIP_ParamCalcIndex
    uint8_t _channelIndex = stripIndex;

    switch (hardwareIndex)
    {
    #ifdef ParamNEOSTRIP_NEOGPIOClockPortHW0
        case 0: return (uint8_t)ParamNEOSTRIP_NEOGPIOClockPortHW0;
    #endif
    #ifdef ParamNEOSTRIP_NEOGPIOClockPortHW1
        case 1: return (uint8_t)ParamNEOSTRIP_NEOGPIOClockPortHW1;
    #endif
    #ifdef ParamNEOSTRIP_NEOGPIOClockPortHW2
        case 2: return (uint8_t)ParamNEOSTRIP_NEOGPIOClockPortHW2;
    #endif
    #ifdef ParamNEOSTRIP_NEOGPIOClockPortHW3
        case 3: return (uint8_t)ParamNEOSTRIP_NEOGPIOClockPortHW3;
    #endif
    #ifdef ParamNEOSTRIP_NEOGPIOClockPortHW4
        case 4: return (uint8_t)ParamNEOSTRIP_NEOGPIOClockPortHW4;
    #endif
    #ifdef ParamNEOSTRIP_NEOGPIOClockPortHW5
        case 5: return (uint8_t)ParamNEOSTRIP_NEOGPIOClockPortHW5;
    #endif
    #ifdef ParamNEOSTRIP_NEOGPIOClockPortHW6
        case 6: return (uint8_t)ParamNEOSTRIP_NEOGPIOClockPortHW6;
    #endif
    #ifdef ParamNEOSTRIP_NEOGPIOClockPortHW7
        case 7: return (uint8_t)ParamNEOSTRIP_NEOGPIOClockPortHW7;
    #endif
    #ifdef ParamNEOSTRIP_NEOGPIOClockPortHW8
        case 8: return (uint8_t)ParamNEOSTRIP_NEOGPIOClockPortHW8;
    #endif
    #ifdef ParamNEOSTRIP_NEOGPIOClockPortHW9
        case 9: return (uint8_t)ParamNEOSTRIP_NEOGPIOClockPortHW9;
    #endif
    #ifdef ParamNEOSTRIP_NEOGPIOClockPortHW10
        case 10: return (uint8_t)ParamNEOSTRIP_NEOGPIOClockPortHW10;
    #endif
    #ifdef ParamNEOSTRIP_NEOGPIOClockPortHW11
        case 11: return (uint8_t)ParamNEOSTRIP_NEOGPIOClockPortHW11;
    #endif
    #ifdef ParamNEOSTRIP_NEOGPIOClockPortHW12
        case 12: return (uint8_t)ParamNEOSTRIP_NEOGPIOClockPortHW12;
    #endif
    #ifdef ParamNEOSTRIP_NEOGPIOClockPortHW13
        case 13: return (uint8_t)ParamNEOSTRIP_NEOGPIOClockPortHW13;
    #endif
    #ifdef ParamNEOSTRIP_NEOGPIOClockPortHW14
        case 14: return (uint8_t)ParamNEOSTRIP_NEOGPIOClockPortHW14;
    #endif
    #ifdef ParamNEOSTRIP_NEOGPIOClockPortHW15
        case 15: return (uint8_t)ParamNEOSTRIP_NEOGPIOClockPortHW15;
    #endif
    #ifdef ParamNEOSTRIP_NEOGPIOClockPortHW16
        case 16: return (uint8_t)ParamNEOSTRIP_NEOGPIOClockPortHW16;
    #endif
    #ifdef ParamNEOSTRIP_NEOGPIOClockPortHW17
        case 17: return (uint8_t)ParamNEOSTRIP_NEOGPIOClockPortHW17;
    #endif
    #ifdef ParamNEOSTRIP_NEOGPIOClockPortHW18
        case 18: return (uint8_t)ParamNEOSTRIP_NEOGPIOClockPortHW18;
    #endif
    #ifdef ParamNEOSTRIP_NEOGPIOClockPortHW19
        case 19: return (uint8_t)ParamNEOSTRIP_NEOGPIOClockPortHW19;
    #endif
    #ifdef ParamNEOSTRIP_NEOGPIOClockPortHW20
        case 20: return (uint8_t)ParamNEOSTRIP_NEOGPIOClockPortHW20;
    #endif
    #ifdef ParamNEOSTRIP_NEOGPIOClockPortHW21
        case 21: return (uint8_t)ParamNEOSTRIP_NEOGPIOClockPortHW21;
    #endif
        default: return DUMMY_GPIO_PORT_SELECTION;
    }
#else
    return DUMMY_GPIO_PORT_SELECTION;
#endif
}

/**
 * @brief Map hardware port index to actual GPIO number
 *
 * Converts a port index (0-9) to the actual GPIO pin number using compile-time defines
 * from platformio.hardware.ini (NEOPIXEL_HW_PORT_N_GPIO).
 *
 * Port indices map to NEOPIXEL_HW_PORT_{index+1}_GPIO defines:
 * - Index 0 → NEOPIXEL_HW_PORT_1_GPIO
 * - Index 1 → NEOPIXEL_HW_PORT_2_GPIO
 * - etc.
 *
 * @param portIndex Port index (0-9) from ETS parameter
 * @return Actual GPIO pin number, or 255 if invalid/not defined
 */
inline uint8_t mapPortIndexToGpio(uint8_t portIndex)
{
    // Port indices 0-9 map to NEOPIXEL_HW_PORT_1_GPIO through NEOPIXEL_HW_PORT_10_GPIO
    switch (portIndex)
    {
#ifdef NEOPIXEL_HW_PORT_1_GPIO
        case 0: return NEOPIXEL_HW_PORT_1_GPIO;
#endif
#ifdef NEOPIXEL_HW_PORT_2_GPIO
        case 1: return NEOPIXEL_HW_PORT_2_GPIO;
#endif
#ifdef NEOPIXEL_HW_PORT_3_GPIO
        case 2: return NEOPIXEL_HW_PORT_3_GPIO;
#endif
#ifdef NEOPIXEL_HW_PORT_4_GPIO
        case 3: return NEOPIXEL_HW_PORT_4_GPIO;
#endif
#ifdef NEOPIXEL_HW_PORT_5_GPIO
        case 4: return NEOPIXEL_HW_PORT_5_GPIO;
#endif
#ifdef NEOPIXEL_HW_PORT_6_GPIO
        case 5: return NEOPIXEL_HW_PORT_6_GPIO;
#endif
#ifdef NEOPIXEL_HW_PORT_7_GPIO
        case 6: return NEOPIXEL_HW_PORT_7_GPIO;
#endif
#ifdef NEOPIXEL_HW_PORT_8_GPIO
        case 7: return NEOPIXEL_HW_PORT_8_GPIO;
#endif
#ifdef NEOPIXEL_HW_PORT_9_GPIO
        case 8: return NEOPIXEL_HW_PORT_9_GPIO;
#endif
#ifdef NEOPIXEL_HW_PORT_10_GPIO
        case 9: return NEOPIXEL_HW_PORT_10_GPIO;
#endif
        default: return INVALID_GPIO;
    }
}

/**
 * @brief Check if hardware-assisted GPIO mode is active
 *
 * Returns true if a valid hardware port is selected (not manual, not dummy).
 *
 * @param portSelection Port-selection value from getDataPortSelectionForHardwareIndex()
 *                      or getClockPortSelectionForHardwareIndex()
 * @return true if hardware port is selected, false if manual (10) or dummy (15)
 */
inline bool isHardwarePortSelected(uint8_t portSelection)
{
    return portSelection <= MAX_HARDWARE_PORT_INDEX;
}

/**
 * @brief Get actual GPIO number for data port
 *
 * High-level function that:
 * 1. Checks if manual mode is enabled
 * 2. If not manual, reads hardware-specific port index
 * 3. Maps port index to actual GPIO number
 *
 * @param stripIndex Strip index (1-based)
 * @param manualGpio Manual GPIO number (from ParamNEOSTRIP_NEODataGPIO)
 * @param isManual Manual mode flag (from ParamNEOSTRIP_NEOGPIOManual)
 * @return Actual GPIO pin number
 */
inline uint8_t getActualDataGpio(uint8_t stripIndex, uint8_t manualGpio, bool isManual)
{
    if (isManual)
    {
        return manualGpio;
    }

    uint8_t portIndex = getDataPortSelectionForHardwareIndex(stripIndex);
    if (isHardwarePortSelected(portIndex))
    {
        return mapPortIndexToGpio(portIndex);
    }

    // Fallback to manual GPIO if hardware port not properly selected
    return manualGpio;
}

/**
 * @brief Get actual GPIO number for clock port (SPI only)
 *
 * Similar to getActualDataGpio but for clock pins.
 *
 * @param stripIndex Strip index (1-based)
 * @param manualGpio Manual GPIO number (from ParamNEOSTRIP_NEOClockGPIO)
 * @param isManual Manual mode flag (from ParamNEOSTRIP_NEOGPIOManual)
 * @return Actual GPIO pin number
 */
inline uint8_t getActualClockGpio(uint8_t stripIndex, uint8_t manualGpio, bool isManual)
{
    if (isManual)
    {
        return manualGpio;
    }

    uint8_t portIndex = getClockPortSelectionForHardwareIndex(stripIndex);
    if (isHardwarePortSelected(portIndex))
    {
        return mapPortIndexToGpio(portIndex);
    }

    // Fallback to manual GPIO if hardware port not properly selected
    return manualGpio;
}
